### ISSUE TITLE
Come up with a better way to supply Maven Central artifacts

### ISSUE THREAD

**Issue by cilki** [AdoptOpenJDK/jlink.online#29]
To bundle external dependencies, you currently have to specify them in both the `modules` parameter and the `artifacts` parameter. For example:
```
GET: /runtime/x64/linux/11.0.8+10?modules=org.slf4j&artifacts=org.slf4j:slf4j-api:2.0.0-alpha1
```

Most people won't be building these by hand, but it's still not very attractive. **I'm thinking of creating a YML or JSON format containing this info that we can ingest instead**. It would still be possible to upload a `module-info.java`, but this new descriptor file would also need to be present to describe the versions of external artifacts. The descriptor could also be given by itself.

Here's an example of something that might work:
```
repositories:
  - https://oss.sonatype.org/content/repositories/snapshots
modules:
  - java.desktop
  - org.slf4j: org.slf4j:slf4j-api:2.0.0-alpha1
```

This file could be committed to version control or automatically generated by a Gradle or Maven plugin. I'm contemplating the uncreative name: `jlink.online.yml`.

The `artifacts` parameter would go away as a result of this change.

**Comment by cilki** [comment]
An improved example:
```
version: 11.0.8+11
os: linux
architecture: x64
modules:
  - java.base
  - org.slf4j
external:
  repositories:
    - https://oss.sonatype.org/content/repositories/snapshots
  artifacts:
    - org.slf4j:slf4j-api:2.0.0-alpha1
```

If no repositories are provided, the default would be `https://repo.maven.apache.org/maven2`.
